plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sinifasistani.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.sinifasistani.app"
        minSdk 24
        targetSdk 34
        versionCode 28
        versionName "1.0.28"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

task copyWebAssets(type: Copy) {
    from '../../dist'
    into 'src/main/assets'
}
preBuild.dependsOn(copyWebAssets)

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.webkit:webkit:1.10.0'
}
